{
 "title": "PROJECT_NAME",
 "time": { "from": "now/d", "to": "now" },
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Average time in seconds",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 1 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(\"createdAt\"),\n  avg(duration) over (partition by \"UserId\")\nFROM\n  \"Kompiles\"\nWHERE\n  $__timeFilter(\"createdAt\") and\n  \"ProjectId\" = PROJECT_ID\n"
    }
   ]
  },
  {
   "title": "Total time",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 1 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(\"createdAt\"),\n  sum(duration) over (partition by \"ProjectId\")\nFROM\n  \"Kompiles\"\nWHERE\n  $__timeFilter(\"createdAt\") and\n  \"ProjectId\" = PROJECT_ID\n"
    }
   ]
  },
  {
   "title": "Min time",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 1 },
   "format": "s",
   "valueName": "min",
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(\"createdAt\"),\n  min(duration) over (partition by \"UserId\")\nFROM\n  \"Kompiles\"\nWHERE\n  $__timeFilter(\"createdAt\") and\n  \"ProjectId\" = PROJECT_ID\n"
    }
   ]
  },
  {
   "title": "Max time",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 1 },
   "format": "dtdurations",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(\"createdAt\"),\n  max(duration) over (partition by \"ProjectId\")\nFROM\n  \"Kompiles\"\nWHERE\n  $__timeFilter(\"createdAt\") and\n  \"ProjectId\" = PROJECT_ID\n"
    }
   ]
  },
  {
   "title": "PROJECT_NAME",
   "type": "graph",
   "gridPos": { "h": 19, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(k.\"createdAt\"),\n  k.duration,\n  u.alias\nFROM\n  \"Kompiles\" k,\n  \"Users\" u\nWHERE\n  $__timeFilter(k.\"createdAt\") and\n  u.id = k.\"UserId\" and\n  \"ProjectId\" = PROJECT_ID\n"
    }
   ]
  }
 ]
}